<a href="https://colab.research.google.com/github/yucachen/MLTSA25_YChen/blob/main/In_Class_Code/PHYS664_Lab_2_11_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
my_str = "hello" # python knows it's a string because of quotes, in C you would need to explicitly tell the code that it is a string

In [5]:
my_str # python notebook will just print out the content of the variable - for any cell, it will return the last line of code in the cell (?)

'hello'

In [7]:
print(my_str) # more formal way of printing variables

hello


In [8]:
my_int = 36

In [12]:
my_float = 3. # must have decimal for python to recognize as a float

In [13]:
print(my_float)

3.0


In [16]:
my_int * my_float # this will become a float, float takes more space/more complex variable --> python will choose the more complex variable

108.0

In [17]:
my_int * my_str # it will repeat this string as many times as the int is

'hellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohello'

In [18]:
my_float * my_str # this will return an error

TypeError: can't multiply sequence by non-int of type 'float'

In [20]:
helloworld = "hello" "world!" # will concatenate together
print(helloworld)

helloworld!


In [21]:
my_nparr = np.array([1, 2, 3])
my_int * my_nparr

array([ 36,  72, 108])

In [22]:
my_bool = True # must capitalize this

In [24]:
my_int == 1

False

In [25]:
my_int != 1

True

In [26]:
if my_int != 36:
  print("my int is not 36")
else:
  print("my int is 36!")

my int is 36!


In [27]:
type(my_int)

int

In [31]:
my_nparr.dtype # without parenthesis, this is a not a method (?)

dtype('int64')

In [33]:
my_nparr.max()

3

In [34]:
my_nparr.argmax() # location of this maximum value

2

In [35]:
my_nparr[0]

1

In [36]:
my_nparr[-1]

3

In [37]:
my_nparr[1:] # colon indicates a range, can take a subset of the array

array([2, 3])

In [39]:
my_nparr[1:3]

array([2, 3])

In [43]:
list(range(1,4))

[1, 2, 3]

In [49]:
for a in range(1,4): # anytime plan on doing some sort of math, please use numpy array or tensors
  print(sum(np.arange(0,a)), 1) # np.arange basically the same as range, but returns np.array type instead of a list/range type (?)

0 1
1 1
3 1


In [66]:
# python stores your entire memory stack, so for some more memory intensive projects (like NN), remember to clear this
# lists are a very flexible data type, so it's a bit easier to use compared to np.array type
def allodds(lastn):
  """
  docstring here! (can put in a string with returns as well)
  prints odd numbers
  input:
    (int) last number in the list
  output:
    a list of odd numbers
  """
  odds = []
  for a in range(0, lastn+1): # to make sure the last integer is returned if it is odd
    if a % 2 == 1:
      odds.append(a)
    # print(odds) # this will print at every part of the loop with this indentation
  return odds

In [67]:
allodds? # this brings up the Help window in Google Colab (?), which then prints out what is in the docstring!

SyntaxError: invalid syntax (<ipython-input-67-4c1fe342c624>, line 1)

In [68]:
allodds(10)

[1, 3, 5, 7, 9]

In [122]:
# own code for checking palindrome
def checkPalindrome(word):

  if type(word) != str:
    print("The variable you provided is not a string! >:(")
    return

  stringLength = float(len(word))

  # for even length word
  if stringLength % 2 == 0. :
    firstHalf = list(word[0:int(stringLength/2)] )
    secondHalf = list(word[int(stringLength/2):])
    secondHalf.reverse()
    if firstHalf == secondHalf:
      return True
    else:
      return False

  # for odd length word
  if stringLength % 2. == 1.:
    firstHalf = list(word[0:int(stringLength/2)+1] )
    # print(firstHalf)
    secondHalf = list(word[int(stringLength/2):])
    # print(secondHalf)
    secondHalf.reverse()
    # print(secondHalf)

    if firstHalf == secondHalf:
      return True
    else:
      return False


In [123]:
checkPalindrome("opo")

['o', 'p']


True

In [126]:
# from class, a more efficient way of doing this

def ispalindrome(s):
  "checks if string is a palindrome"
  assert type(s) == str, "is not a string"
  if s.lower() == s[::-1].lower():
    return True
  return False

In [127]:
ispalindrome("tacocat")

True